name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  release:
    uses: theholocron/.github/.github/workflows/release.yml@main
    secrets: inherit
